### ISSUE TITLE
Changing LLM to Llama 2 13b

### ISSUE THREAD

**Issue by memowrecks** [edgar971/open-chat#16]
I am attempting to change the default Llama 2 7b to the 13b variant. 

I have downloaded the model, and placed it in the models folder: /models/llama-2-13b-chat.ggmlv3.q4_0.bin

I have configured the download URL to: https://huggingface.co/TheBloke/Llama-2-13B-chat-GGML/blob/main/llama-2-13b-chat.ggmlv3.q4_0.bin 

But now all I get is a spinning wheel in the UI - it doesn't seem to load the LLM 

![image](https://github.com/edgar971/open-chat/assets/157701923/955934b4-4a59-4c57-b812-2a39c3f6b8ee)

![image](https://github.com/edgar971/open-chat/assets/157701923/e5fce5ac-0c47-47ad-9092-fc5fd2dcf3f7)

**Comment by ClashC** [comment]
I have the same behavior. What was the solution here?

Edit: Ok, i rename local model path name to llama-2-13b-chat.bin and now is ok... :)
